name: Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: read

jobs:

  release-cosmo:
    permissions:
      contents: write  # for softprops/action-gh-release to create GitHub release
    name: Build release binaries for Cosmo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@master
      - name: create build folder
        run: |
          sudo mkdir -p /sc
          sudo chmod -R 0777 /sc
      - name: build APE binary of gguf-tools
        run: bash ./.github/cosmo/build
      - name: push binary to github
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: |
            gguf-tools
